version: "3"
services: 
  springboot-app:
   # container_name: spring-app
    image: jcaf/shows:1.0
    build: .
    ports:
      - "8080:8080"
    depends_on:
     - mariadb  
    environment:
      MYSQL_HOST: mariadb
      MYSQL_PORT: 3306
      passwdAdm: 
      userBd: 
      passwdBd: 
      mercadoPagoAccessToken: 
  mariadb: 
    container_name: mariadb
    image: mariadb:11.0.2
    ports: 
     - "3306:3306"   
    environment:
      MYSQL_DATABASE: shows
      MYSQL_ROOT_PASSWORD: 
      MYSQL_PASSWORD: 
